# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-31 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='arabeasy_word',
            new_name='arabizi_word',
        ),
    ]
