# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-31 20:12
from __future__ import unicode_literals

import dictionary.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_auto_20180731_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='arabizi_word',
            field=models.CharField(max_length=20, validators=[dictionary.validators.validate_not_arabic]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='english_definition',
            field=models.CharField(max_length=150, validators=[dictionary.validators.validate_not_arabic]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='script_word',
            field=models.CharField(max_length=20, validators=[dictionary.validators.validate_arabic]),
        ),
    ]
