# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-31 20:23
from __future__ import unicode_literals

import dictionary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0008_auto_20180731_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='dialect',
            field=models.CharField(choices=[(dictionary.models.Dialects('Levantine'), 'Levantine'), (dictionary.models.Dialects('Egyptian'), 'Egyptian'), (dictionary.models.Dialects('Gulf'), 'Gulf')], max_length=9),
        ),
        migrations.AlterField(
            model_name='entry',
            name='part_of_speech',
            field=models.CharField(choices=[(dictionary.models.PartsOfSpeech('Verb'), 'Verb'), (dictionary.models.PartsOfSpeech('Noun'), 'Noun'), (dictionary.models.PartsOfSpeech('Particle'), 'Particle'), (dictionary.models.PartsOfSpeech('Pronoun'), 'Pronoun'), (dictionary.models.PartsOfSpeech('Adjective'), 'Adjective'), (dictionary.models.PartsOfSpeech('Adverb'), 'Adverb'), (dictionary.models.PartsOfSpeech('Preposition'), 'Preposition'), (dictionary.models.PartsOfSpeech('Interjection'), 'Interjection')], max_length=3),
        ),
    ]
