# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-03 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0012_auto_20180803_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='part_of_speech',
            field=models.CharField(choices=[('V', 'Verb'), ('N', 'Noun'), ('P', 'Particle'), ('PN', 'Pronoun'), ('ADJ', 'Adjective'), ('ADV', 'Adverb'), ('PRE', 'Preposition'), ('I', 'Interjection')], max_length=3),
        ),
    ]
