# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-04 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0014_auto_20180803_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='part_of_speech',
            field=models.CharField(choices=[('Verb', 'Verb'), ('Noun', 'Noun'), ('Particle', 'Particle'), ('Pronoun', 'Pronoun'), ('Adjective', 'Adjective'), ('Adverb', 'Adverb'), ('Preposition', 'Preposition'), ('Interjection', 'Interjection')], max_length=15),
        ),
    ]
