# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-30 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_language'),
        ('accounts', '0004_auto_20180726_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='other_languages',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='target_languages',
        ),
        migrations.AddField(
            model_name='profile',
            name='target_dialects',
            field=models.ManyToManyField(related_name='target_languages', to='dictionary.Language'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='native_languages',
            field=models.ManyToManyField(related_name='native_languages', to='dictionary.Language'),
        ),
    ]
